name: Deploy Two Services

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ vars.DOCKERHUB_TOKEN }}
      
      - name: Build and push QuizApp image
        uses: docker/build-push-action@v4
        with:
          context: ./QuizApp
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/quizapp:latest
      
      - name: Build and push QuizApi image
        uses: docker/build-push-action@v4
        with:
          context: ./QuizApi
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/quizapi:latest

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ vars.PEM_KEY }}" > ~/.ssh/priv.pem
          chmod 600 ~/.ssh/priv.pem
          ssh-keyscan -H ${{ vars.HOST }} >> ~/.ssh/known_hosts

      - name: SSH and Deploy Docker Containers
        run: |
          ssh -i ~/.ssh/priv.pem ${{ vars.USERNAME }}@${{ vars.HOST }} << 'EOF'
            # Pull the latest images
            docker pull ${{ vars.DOCKERHUB_USERNAME }}/quizapp:latest
            docker pull ${{ vars.DOCKERHUB_USERNAME }}/quizapi:latest

            # Stop running containers
            docker stop quizapp || true
            docker stop quizapi || true
            docker rm quizapp || true
            docker rm quizapi || true

            # Start QuizApi container
            docker run -d \
              --name quizapi \
              -p 5000:5000 \
              -e MONGO_URI=${{ vars.MONGO_URI }} \
              --restart unless-stopped \
              ${{ vars.DOCKERHUB_USERNAME }}/quizapi:latest

            # Start QuizApp container
            docker run -d \
              --name quizapp \
              -p 3000:3000 \
              -e REACT_APP_API_URL=${{ vars.API }} \
              --restart unless-stopped \
              ${{ vars.DOCKERHUB_USERNAME }}/quizapp:latest
          EOF
