name: Deploy Two Services

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PEM_KEY }}" > ~/.ssh/priv.pem
          chmod 600 ~/.ssh/priv.pem
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: SSH and Deploy Both Services
        run: |
          ssh -i ~/.ssh/priv.pem ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
            cd ${{ secrets.APP_DIR }}
            git pull origin main

            # Service A
            cd ~/cs218quizapp/QuizApp
            yarn start
            screen -S web -X quit || true
            screen -S web -dm bash -c "yarn dev"

            # Service B
            cd  ~/cs218quizapp/QuizApi
            npm install
            screen -S api -X quit || true
            screen -S api -dm bash -c "node api"
          EOF
